#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : cogl
Version  : 1.22.8
Release  : 37
URL      : https://download.gnome.org/sources/cogl/1.22/cogl-1.22.8.tar.xz
Source0  : https://download.gnome.org/sources/cogl/1.22/cogl-1.22.8.tar.xz
Summary  : An object oriented GL/GLES Abstraction/Utility Layer
Group    : Development/Tools
License  : LGPL-2.0 MIT
Requires: cogl-data = %{version}-%{release}
Requires: cogl-lib = %{version}-%{release}
Requires: cogl-license = %{version}-%{release}
Requires: cogl-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : buildreq-gnome
BuildRequires : cairo-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : mesa-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(sdl)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===============================================================================
Note: This file is delimited with -- markers so it is possible to split
sections out for other purposes, such as for release notes.

%package data
Summary: data components for the cogl package.
Group: Data

%description data
data components for the cogl package.


%package dev
Summary: dev components for the cogl package.
Group: Development
Requires: cogl-lib = %{version}-%{release}
Requires: cogl-data = %{version}-%{release}
Provides: cogl-devel = %{version}-%{release}
Requires: cogl = %{version}-%{release}

%description dev
dev components for the cogl package.


%package lib
Summary: lib components for the cogl package.
Group: Libraries
Requires: cogl-data = %{version}-%{release}
Requires: cogl-license = %{version}-%{release}

%description lib
lib components for the cogl package.


%package license
Summary: license components for the cogl package.
Group: Default

%description license
license components for the cogl package.


%package locales
Summary: locales components for the cogl package.
Group: Default

%description locales
locales components for the cogl package.


%prep
%setup -q -n cogl-1.22.8
cd %{_builddir}/cogl-1.22.8
pushd ..
cp -a cogl-1.22.8 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685491965
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static --enable-cogl-gles2=yes \
--enable-gles2=yes \
--enable-gl=yes \
--enable-wayland-egl-platform=yes \
--enable-wayland-egl-server=yes
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static --enable-cogl-gles2=yes \
--enable-gles2=yes \
--enable-gl=yes \
--enable-wayland-egl-platform=yes \
--enable-wayland-egl-server=yes
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1685491965
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cogl
cp %{_builddir}/cogl-%{version}/COPYING %{buildroot}/usr/share/package-licenses/cogl/c40ca709f2b0391c439d2a9dce38541da745a1b9 || :
cp %{_builddir}/cogl-%{version}/deps/glib/COPYING %{buildroot}/usr/share/package-licenses/cogl/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang cogl
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Cogl-1.0.typelib
/usr/lib64/girepository-1.0/Cogl-2.0.typelib
/usr/lib64/girepository-1.0/CoglPango-1.0.typelib
/usr/lib64/girepository-1.0/CoglPango-2.0.typelib
/usr/share/cogl/examples-data/crate.jpg
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/cogl/cogl-gles2/GLES2/gl2.h
/usr/include/cogl/cogl-gles2/GLES2/gl2ext.h
/usr/include/cogl/cogl-gles2/GLES2/gl2platform.h
/usr/include/cogl/cogl-pango/cogl-pango.h
/usr/include/cogl/cogl-path/cogl-path-enum-types.h
/usr/include/cogl/cogl-path/cogl-path-types.h
/usr/include/cogl/cogl-path/cogl-path.h
/usr/include/cogl/cogl-path/cogl1-path-functions.h
/usr/include/cogl/cogl-path/cogl2-path-functions.h
/usr/include/cogl/cogl/cogl-atlas-texture.h
/usr/include/cogl/cogl/cogl-attribute-buffer.h
/usr/include/cogl/cogl/cogl-attribute.h
/usr/include/cogl/cogl/cogl-auto-texture.h
/usr/include/cogl/cogl/cogl-bitmap.h
/usr/include/cogl/cogl/cogl-buffer.h
/usr/include/cogl/cogl/cogl-clip-state.h
/usr/include/cogl/cogl/cogl-clutter-xlib.h
/usr/include/cogl/cogl/cogl-clutter.h
/usr/include/cogl/cogl/cogl-color.h
/usr/include/cogl/cogl/cogl-context.h
/usr/include/cogl/cogl/cogl-defines.h
/usr/include/cogl/cogl/cogl-deprecated.h
/usr/include/cogl/cogl/cogl-depth-state.h
/usr/include/cogl/cogl/cogl-display.h
/usr/include/cogl/cogl/cogl-egl-defines.h
/usr/include/cogl/cogl/cogl-egl.h
/usr/include/cogl/cogl/cogl-enum-types.h
/usr/include/cogl/cogl/cogl-error.h
/usr/include/cogl/cogl/cogl-euler.h
/usr/include/cogl/cogl/cogl-fence.h
/usr/include/cogl/cogl/cogl-fixed.h
/usr/include/cogl/cogl/cogl-frame-info.h
/usr/include/cogl/cogl/cogl-framebuffer-deprecated.h
/usr/include/cogl/cogl/cogl-framebuffer.h
/usr/include/cogl/cogl/cogl-gles2-types.h
/usr/include/cogl/cogl/cogl-gles2.h
/usr/include/cogl/cogl/cogl-glib-source.h
/usr/include/cogl/cogl/cogl-glx.h
/usr/include/cogl/cogl/cogl-index-buffer.h
/usr/include/cogl/cogl/cogl-indices.h
/usr/include/cogl/cogl/cogl-macros.h
/usr/include/cogl/cogl/cogl-material-compat.h
/usr/include/cogl/cogl/cogl-matrix-stack.h
/usr/include/cogl/cogl/cogl-matrix.h
/usr/include/cogl/cogl/cogl-meta-texture.h
/usr/include/cogl/cogl/cogl-object.h
/usr/include/cogl/cogl/cogl-offscreen.h
/usr/include/cogl/cogl/cogl-onscreen-template.h
/usr/include/cogl/cogl/cogl-onscreen.h
/usr/include/cogl/cogl/cogl-output.h
/usr/include/cogl/cogl/cogl-pango.h
/usr/include/cogl/cogl/cogl-pipeline-layer-state.h
/usr/include/cogl/cogl/cogl-pipeline-state.h
/usr/include/cogl/cogl/cogl-pipeline.h
/usr/include/cogl/cogl/cogl-pixel-buffer.h
/usr/include/cogl/cogl/cogl-poll.h
/usr/include/cogl/cogl/cogl-primitive-texture.h
/usr/include/cogl/cogl/cogl-primitive.h
/usr/include/cogl/cogl/cogl-primitives.h
/usr/include/cogl/cogl/cogl-quaternion.h
/usr/include/cogl/cogl/cogl-renderer.h
/usr/include/cogl/cogl/cogl-shader.h
/usr/include/cogl/cogl/cogl-snippet.h
/usr/include/cogl/cogl/cogl-sub-texture.h
/usr/include/cogl/cogl/cogl-swap-chain.h
/usr/include/cogl/cogl/cogl-texture-2d-gl.h
/usr/include/cogl/cogl/cogl-texture-2d-sliced.h
/usr/include/cogl/cogl/cogl-texture-2d.h
/usr/include/cogl/cogl/cogl-texture-3d.h
/usr/include/cogl/cogl/cogl-texture-deprecated.h
/usr/include/cogl/cogl/cogl-texture-pixmap-x11.h
/usr/include/cogl/cogl/cogl-texture-rectangle.h
/usr/include/cogl/cogl/cogl-texture.h
/usr/include/cogl/cogl/cogl-type-casts.h
/usr/include/cogl/cogl/cogl-types.h
/usr/include/cogl/cogl/cogl-vector.h
/usr/include/cogl/cogl/cogl-version.h
/usr/include/cogl/cogl/cogl-vertex-buffer.h
/usr/include/cogl/cogl/cogl-wayland-client.h
/usr/include/cogl/cogl/cogl-wayland-renderer.h
/usr/include/cogl/cogl/cogl-wayland-server.h
/usr/include/cogl/cogl/cogl-xlib-renderer.h
/usr/include/cogl/cogl/cogl-xlib.h
/usr/include/cogl/cogl/cogl.h
/usr/include/cogl/cogl/cogl1-context.h
/usr/include/cogl/cogl/cogl2-experimental.h
/usr/include/cogl/cogl/deprecated/cogl-auto-texture.h
/usr/include/cogl/cogl/deprecated/cogl-clip-state.h
/usr/include/cogl/cogl/deprecated/cogl-clutter-xlib.h
/usr/include/cogl/cogl/deprecated/cogl-clutter.h
/usr/include/cogl/cogl/deprecated/cogl-fixed.h
/usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h
/usr/include/cogl/cogl/deprecated/cogl-material-compat.h
/usr/include/cogl/cogl/deprecated/cogl-shader.h
/usr/include/cogl/cogl/deprecated/cogl-texture-deprecated.h
/usr/include/cogl/cogl/deprecated/cogl-type-casts.h
/usr/include/cogl/cogl/deprecated/cogl-vertex-buffer.h
/usr/include/cogl/cogl/gl-prototypes/cogl-core-functions.h
/usr/include/cogl/cogl/gl-prototypes/cogl-gles2-functions.h
/usr/include/cogl/cogl/gl-prototypes/cogl-glsl-functions.h
/usr/include/cogl/cogl/gl-prototypes/cogl-in-gles-core-functions.h
/usr/include/cogl/cogl/gl-prototypes/cogl-in-gles2-core-functions.h
/usr/lib64/libcogl-gles2.so
/usr/lib64/libcogl-pango.so
/usr/lib64/libcogl-path.so
/usr/lib64/libcogl.so
/usr/lib64/pkgconfig/cogl-1.0.pc
/usr/lib64/pkgconfig/cogl-2.0-experimental.pc
/usr/lib64/pkgconfig/cogl-gl-1.0.pc
/usr/lib64/pkgconfig/cogl-gles2-1.0.pc
/usr/lib64/pkgconfig/cogl-gles2-2.0-experimental.pc
/usr/lib64/pkgconfig/cogl-pango-1.0.pc
/usr/lib64/pkgconfig/cogl-pango-2.0-experimental.pc
/usr/lib64/pkgconfig/cogl-path-1.0.pc
/usr/lib64/pkgconfig/cogl-path-2.0-experimental.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcogl-gles2.so.20.4.3
/V3/usr/lib64/libcogl-pango.so.20.4.3
/V3/usr/lib64/libcogl-path.so.20.4.3
/V3/usr/lib64/libcogl.so.20.4.3
/usr/lib64/libcogl-gles2.so.20
/usr/lib64/libcogl-gles2.so.20.4.3
/usr/lib64/libcogl-pango.so.20
/usr/lib64/libcogl-pango.so.20.4.3
/usr/lib64/libcogl-path.so.20
/usr/lib64/libcogl-path.so.20.4.3
/usr/lib64/libcogl.so.20
/usr/lib64/libcogl.so.20.4.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cogl/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f
/usr/share/package-licenses/cogl/c40ca709f2b0391c439d2a9dce38541da745a1b9

%files locales -f cogl.lang
%defattr(-,root,root,-)

